#+title: React & Vite Project 02

* React + Vite
This template provides a minimal setup to get React working in Vite with HMR and some ESLint rules.

Currently, two official plugins are available:

- [[https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/README.md][vitejs/plugin-react]] uses [[https://babeljs.io/][Babel]] for Fast Refresh
- [[https://github.com/vitejs/vite-plugin-react-swc][vitejs/plugin-react-swc]] uses [[https://swc.rs/][SWC]] for Fast Refresh

* Create the Project
+ The following command is going to create the project.
+ Then just answer the different questions generated by the script to complete the process of creation
#+begin_src bash
npm init vite@latest
#+end_src

* Start the Server
#+begin_src bash
npm run dev
#+end_src

* Dependencies
** Styles Components (Emotion React & Styled)
+ It is basically an alternative to style components. It has the same benefit of tailwind regarding once you don't need the component, you can get rid of it altogether with its styles. So the project won't have unused styles.
+ The disadvantage is that the styles will be altogether with the jsx files. So the code will be less clean, similar to tailwind.
*** Installation
#+begin_src bash
npm install @emotion/react @emotion/styled
#+end_src

* Deployment
