#+title: React & Vite Project 03

* React + Vite
This template provides a minimal setup to get React working in Vite with HMR and some ESLint rules.

Currently, two official plugins are available:

- [[https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/README.md][vitejs/plugin-react]] uses [[https://babeljs.io/][Babel]] for Fast Refresh
- [[https://github.com/vitejs/vite-plugin-react-swc][vitejs/plugin-react-swc]] uses [[https://swc.rs/][SWC]] for Fast Refresh

* Create the Project
+ The following command is going to create the project.
+ Then just answer the different questions generated by the script to complete the process of creation
#+begin_src bash
npm init vite@latest
#+end_src

* Start the Server
#+begin_src bash
npm run dev
#+end_src

* Dependencies
** Styles Components (Emotion React & Styled)
+ It is basically an alternative to style components. It has the same benefit of tailwind regarding once you don't need the component, you can get rid of it altogether with its styles. So the project won't have unused styles.
+ The disadvantage is that the styles will be altogether with the jsx files. So the code will be less clean, similar to tailwind.
*** Installation
#+begin_src bash
npm install @emotion/react @emotion/styled
#+end_src

* Create your own Hook
+ It is an alternative to a helper file that contains functions you will usually need in your projects
+ It brings some react benefits over a helper files like the use of States, Effects, keep a function value in persistent monde, among others react benefits.
+ It is similar to your regular react components but it doesn't return html, instead it returns an object, array, funtion or other regular javascript values

* Deployment
[[https://incomparable-biscuit-c11bac.netlify.app/][Link to deployment]]
